# Factor III: Config - Configurazione tramite environment variables
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: twelve-factor-demo

# Factor XI: Logs - Scrive su stdout
logging:
  level:
    root: INFO
    it.alf.twelve-factor-demo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Factor XII: Admin processes - Gestione amministrativa
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# Application specific config
app:
  greeting:
    prefix: ${GREETING_PREFIX:Hello}
  version: ${APP_VERSION:1.0.0}